name: release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Remove source files
        run: |
          rm ./pack/assets/minecraft/lang/en_us.json
          rm ./pack/assets/minecraft/lang/ja_jp.json

      - name: Generate Kana
        run: bin/generate_kana

      - name: Create archive
        run: |
          cd pack
          zip -r ../minecraft-ainu.zip .

      - name: Upload asset
        run: gh release upload "${{ github.ref_name }}" minecraft-ainu.zip --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
